---
version: '3.7'
services:
  db:
    build: derby
    ports:
      - 1527:1527
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
      - "4848:4848"
